### ISSUE TITLE
telestion-rx-wind-importer

### ISSUE THREAD

**Issue by jvpichowski** [TelestionTeam/telestion#12]
This verticle should import the wind data which is provided by SNSC during flight.

**Tasks**
- [x] get some wind files of old flights
- [ ] write down the requirements
- [ ] write a csv parser to interprete the files
- [ ] write an upload service to import the files using the Vert.x api.
- [ ] drop the data on the event bus
- [ ] write unit tests

**Comment by jvpichowski** [comment]
No progress from the Daedalus Simulation Team. So we put this on hold.
